from pydantic import BaseModel
from typing import Optional, List, Dict, Any

class Address(BaseModel):
    id: Optional[str]
    rowNumber: Optional[int]
    note: Optional[str]
    AddressLine1: Optional[Dict[str, Any]]
    AddressLine2: Optional[Dict[str, Any]]
    City: Optional[Dict[str, Any]]
    Country: Optional[Dict[str, Any]]
    PostalCode: Optional[Dict[str, Any]]
    State: Optional[Dict[str, Any]]
    custom: Optional[Dict[str, Any]]
    files: Optional[List]

class Contact(BaseModel):
    id: Optional[str]
    rowNumber: Optional[int]
    note: Optional[str]
    Address: Address
    DisplayName: Optional[Dict[str, Any]]
    Email: Optional[Dict[str, Any]]
    Fax: Optional[Dict[str, Any]]
    FirstName: Optional[Dict[str, Any]]
    LastName: Optional[Dict[str, Any]]
    MiddleName: Optional[Dict[str, Any]]
    Phone1: Optional[Dict[str, Any]]
    Phone1Type: Optional[Dict[str, Any]]
    Phone2: Optional[Dict[str, Any]]
    Phone2Type: Optional[Dict[str, Any]]
    Title: Optional[Dict[str, Any]]
    custom: Optional[Dict[str, Any]]
    files: Optional[List]

class EmploymentHistory(BaseModel):
    id: Optional[str]
    rowNumber: Optional[int]
    note: Optional[str]
    Active: Optional[Dict[str, Any]]
    EndDate: Optional[Dict[str, Any]]
    LineNbr: Optional[Dict[str, Any]]
    PositionID: Optional[Dict[str, Any]]
    RehireEligible: Optional[Dict[str, Any]]
    StartDate: Optional[Dict[str, Any]]
    StartReason: Optional[Dict[str, Any]]
    Terminated: Optional[Dict[str, Any]]
    TerminationReason: Optional[Dict[str, Any]]
    custom: Optional[Dict[str, Any]]
    files: Optional[List]

class PaymentInstruction(BaseModel):
    id: Optional[str]
    rowNumber: Optional[int]
    note: Optional[str]
    BAccountID: Optional[Dict[str, Any]]
    Description: Optional[Dict[str, Any]]
    InstructionID: Optional[Dict[str, Any]]
    LocationID: Optional[Dict[str, Any]]
    PaymentMethod: Optional[Dict[str, Any]]
    Value: Optional[Dict[str, Any]]
    custom: Optional[Dict[str, Any]]
    files: Optional[List]

class EmployeeResponse(BaseModel):
    id: str
    rowNumber: Optional[int]
    note: Optional[str]
    BranchID: Optional[Dict[str, Any]]
    Calendar: Optional[Dict[str, Any]]
    CashAccount: Optional[Dict[str, Any]]
    Contact: Contact
    CurrencyID: Optional[Dict[str, Any]]
    DateOfBirth: Optional[Dict[str, Any]]
    DepartmentID: Optional[Dict[str, Any]]
    EmployeeClassID: Optional[Dict[str, Any]]
    EmployeeID: Optional[Dict[str, Any]]
    EmploymentHistory: List[EmploymentHistory]
    ExpenseAccount: Optional[Dict[str, Any]]
    ExpenseSubaccount: Optional[Dict[str, Any]]
    IdentityNumber: Optional[Dict[str, Any]]
    IdentityType: Optional[Dict[str, Any]]
    LastModifiedDateTime: Optional[Dict[str, Any]]
    Name: Optional[Dict[str, Any]]
    PaymentInstruction: List[PaymentInstruction]
    PaymentMethod: Optional[Dict[str, Any]]
    ReportsToID: Optional[Dict[str, Any]]
    SalesAccount: Optional[Dict[str, Any]]
    SalesSubaccount: Optional[Dict[str, Any]]
    Status: Optional[Dict[str, Any]]
    custom: Optional[Dict[str, Any]]
    links: Optional[Dict[str, Any]]
    files: Optional[List]
