from sqlalchemy import create_engine, Column, String, Integer, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

SQLALCHEMY_DATABASE_URL = "mssql+pyodbc://sa:sa%40121314@localhost:1433/MiHRS?driver=ODBC+Driver+17+for+SQL+Server"

engine = create_engine(SQLALCHEMY_DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class Employee(Base):
    __tablename__ = 'employee'

    id = Column(String(36), primary_key=True, index=True)
    row_number = Column(Integer, nullable=True)
    note = Column(String, nullable=True)
    BranchID = Column(String(30), nullable=True)
    Calendar = Column(String(30), nullable=True)
    CashAccount = Column(String(30), nullable=True)
    ContactID = Column(String(36), nullable=True)
    ContactRowNumber = Column(Integer, nullable=True)
    ContactNote = Column(String, nullable=True)
    ContactDisplayName = Column(String, nullable=True)
    ContactEmail = Column(String, nullable=True)
    ContactFax = Column(String, nullable=True)
    ContactFirstName = Column(String, nullable=True)
    ContactLastName = Column(String, nullable=True)
    ContactMiddleName = Column(String, nullable=True)
    ContactPhone1 = Column(String, nullable=True)
    ContactPhone1Type = Column(String, nullable=True)
    ContactPhone2 = Column(String, nullable=True)
    ContactPhone2Type = Column(String, nullable=True)
    ContactTitle = Column(String, nullable=True)
    AddressID = Column(String(36), nullable=True)
    AddressRowNumber = Column(Integer, nullable=True)
    AddressNote = Column(String, nullable=True)
    AddressLine1 = Column(String, nullable=True)
    AddressLine2 = Column(String, nullable=True)
    AddressCity = Column(String, nullable=True)
    AddressCountry = Column(String(10), nullable=True)
    AddressPostalCode = Column(String, nullable=True)
    AddressState = Column(String, nullable=True)
    CurrencyID = Column(String(10), nullable=True)
    DateOfBirth = Column(DateTime, nullable=True)
    DepartmentID = Column(String(30), nullable=True)
    EmployeeClassID = Column(String(10), nullable=True)
    EmployeeID = Column(String(30), nullable=True)
    EmploymentHistoryID = Column(String(36), nullable=True)
    EmploymentHistoryRowNumber = Column(Integer, nullable=True)
    EmploymentHistoryNote = Column(String, nullable=True)
    EmploymentHistoryActive = Column(Boolean, nullable=True)
    EmploymentHistoryEndDate = Column(DateTime, nullable=True)
    EmploymentHistoryLineNbr = Column(Integer, nullable=True)
    EmploymentHistoryPositionID = Column(String(30), nullable=True)
    EmploymentHistoryRehireEligible = Column(Boolean, nullable=True)
    EmploymentHistoryStartDate = Column(DateTime, nullable=True)
    EmploymentHistoryStartReason = Column(String, nullable=True)
    EmploymentHistoryTerminated = Column(Boolean, nullable=True)
    EmploymentHistoryTerminationReason = Column(String, nullable=True)
    ExpenseAccount = Column(String(30), nullable=True)
    ExpenseSubaccount = Column(String(30), nullable=True)
    IdentityNumber = Column(String(30), nullable=True)
    IdentityType = Column(String(30), nullable=True)
    LastModifiedDateTime = Column(DateTime, nullable=True)
    Name = Column(String, nullable=True)
    PaymentInstructionID = Column(String(36), nullable=True)
    PaymentInstructionRowNumber = Column(Integer, nullable=True)
    PaymentInstructionNote = Column(String, nullable=True)
    PaymentInstructionBAccountID = Column(Integer, nullable=True)
    PaymentInstructionDescription = Column(String, nullable=True)
    PaymentInstructionInstructionID = Column(String(30), nullable=True)
    PaymentInstructionLocationID = Column(Integer, nullable=True)
    PaymentInstructionMethod = Column(String(10), nullable=True)
    PaymentInstructionValue = Column(String, nullable=True)
    PaymentMethod = Column(String(10), nullable=True)
    ReportsToID = Column(String(30), nullable=True)
    SalesAccount = Column(String(30), nullable=True)
    SalesSubaccount = Column(String(30), nullable=True)
    Status = Column(String(30), nullable=True)
    Custom = Column(String, nullable=True)
    Links = Column(String, nullable=True)

# Create the database tables if they don't exist
Base.metadata.create_all(bind=engine)
